apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: keycloak-skaffold
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      helm:
        releases:
          - name: keycloak
            chartPath: helm/
            namespace: keycloak
            createNamespace: true
  - name: prod
    deploy:
      helm:
        releases:
          - name: keycloak
            chartPath: helm
            namespace: keycloak
            createNamespace: true
            valuesFiles:
              - helm/values-prod.yaml
            wait: true
            upgradeOnChange: true
