apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: {{ .Values.keycloak.instanceCount }}
  http:
    httpEnabled: {{ .Values.keycloak.httpEnabled }}
    # tlsSecret: example-tls-secret  # For HTTPS, but gateway and mTLS handles this
  hostname:
    hostname: {{ .Values.keycloak.hostname }}
  bootstrapAdmin:
    service:
      secret: {{ .Values.keycloak.bootstrap.admin.service }}
    {{- if .Values.keycloak.bootstrap.admin.user }}
    user:
      secret: {{ .Values.keycloak.bootstrap.admin.user }}
    {{- end }}
  db:
    database: "keycloak"
    host: "postgres"
    vendor: "postgres"
    usernameSecret:
      name: keycloak-database-secret
      key: username
    passwordSecret:
      name: keycloak-database-secret
      key: password
  proxy:
    headers: "forwarded"
  httpManagement:
    port: 9000


