apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  http:
    httpEnabled: true
    # tlsSecret: example-tls-secret  # Optional: for HTTPS
  hostname:
    hostname: keycloak.local
  bootstrapAdmin:
    service:
      secret: keycloak-bootstrap-service-secret
    # user:
    #   secret: keycloak-bootstrap-user-secret
  db:
    database: "keycloak"
    host: "postgres"
    vendor: "postgres"
    usernameSecret:
      name: keycloak-database-secret
      key: username
    passwordSecret:
      name: keycloak-database-secret
      key: password
  proxy:
    headers: "forwarded"


