apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-encrypted-ingress
spec:
  podSelector:
    matchLabels:
      app: keycloak
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 15008
