apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secrets-manager
spec:
  provider:
    vault:
      server: "http://secrets-manager-openbao.secrets-manager.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "auth-manager-role"
          serviceAccountRef:
            name: "keycloak-operator"
